#station_list:
#  - Øvre Leirbotn
#  - ØVERBYGD II
#  - Siccajavvre
#  - Storstilla ndf
#  - Namsvatn tunnel
#  - Svarttjønnbekken Klima
#  - Maurhaugen - Oppdal
#  - Grimsa snøpute
#  - Anestølen
#  - Kyrkjestølane
#  - Vetlebotn
#  - Bakko
#  - Groset
#  - Brunkollen klima
#  - Nedre Sjodalsvatn
#  - Øvre Heimdalsvatn
station_name:
  - Øvre Leirbotn
  - ØVERBYGD II
  - Siccajavvre
  - Storstilla ndf
  - Namsvatn tunnel
  - Svarttjønnbekken Klima
  - Maurhaugen - Oppdal
  - Grimsa snøpute
  - Anestølen
  - Kyrkjestølane
  - Vetlebotn
  - Bakko
  - Groset
  - Brunkollen klima
  - Nedre Sjodalsvatn
  - Øvre Heimdalsvatn

features:
  - swe
  - temperatur
  - relative humidity
  - wind direction and speed
  - precipitation
  - wind speed
  - snow depth
  - ground water level
  - discharge
  - reservoir volume

start_time:
  - 01 # day
  - 12 # month
  - 2001 # year

end_time:
  - 30 # day
  - 11 # month
  - 2021 # year
output_path:
  "../data"
save_name:
  "data_hyperparameter_tuning.csv"
time_resolution:
  - day
  #- hour
  #- as_measured


# Configurations for preparation steps:
run_preparation: True                                 # Whether we want to run further preparation steps of downloaded data
drop_cols: 0.55                                       # Drop all columns which contain more NA values then given share
threshold_linear_inter: 0.55                          # If Total Na Values smaller then threshold, then make interpolation, otherwise take mean values of other years
fill_nan_method: "fill_nan_by_same_features_avg"      # Set to the name of one function of: ["fill_nan_by_daily_avg", "fill_nan_by_same_features_avg"]
consecutive_days_with_nulls: 90                       # If the overall number of Null values is less then specified per year and column we will interpolate

# Specify how to interpolate
interpolation_method: "linear"                        # How to interpolate NA Values
order_interpolation: 3                                # Which order to use for interpolation (if interpolation in ["polynomial", "spline"], can still be defined, eventhough e.g. linear interpolation doesnt require order

# Specify as list of strings which columns to plot before/ after interpolation
# Possible input Columns are: "{station_name}/ {feature}"
plot_columns: ["Øvre Leirbotn/ swe", "Groset/ swe"]